matrix:
  include:
    - language: java
      jdk: oraclejdk8
      before_script:
        - cd server
      script:
        - gradle check
        - gradle jacocoTestReport
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
      after_success:
        bash <(curl -s https://codecov.io/bash) -cF java
    - language: node_js
      node_js:
        - "node"
      install:
      - npm install -g codecov
      before_script:
        - cd client
        - npm install
      cache:
        directories:
          - "node_modules"
      script:
        - npm test
        - npm run coverage
        - codecov
      after_success:
        bash <(curl -s https://codecov.io/bash) -cF javascript

notifications:
    email: false
